import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
  alias(libs.plugins.kotlinMultiplatform)
  alias(libs.plugins.androidLibrary)
  alias(libs.plugins.sqldelight)
}

kotlin {
  androidTarget {
    compilerOptions {
      jvmTarget = JvmTarget.JVM_11
    }
  }

  iosArm64()
  iosSimulatorArm64()

  jvm()

  js {
    browser()
  }

  wasmJs {
    browser()
  }

  sourceSets {
    commonMain {
      dependencies {
        implementation libs.kotlinx.coroutinesCore
        implementation libs.kotlinx.datetime
        implementation libs.sqldelight.runtime
        implementation libs.sqldelight.coroutinesExtensions
      }
    }
    commonTest {
      dependencies {
        implementation libs.kotlin.test
      }
    }
    androidMain {
      dependencies {
        implementation libs.sqldelight.androidDriver
      }
    }
    iosMain {
      dependencies {
        implementation libs.sqldelight.nativeDriver
      }
    }
    jvmMain {
      dependencies {
        implementation libs.sqldelight.sqliteDriver
      }
    }
  }
}

android {
  namespace = "com.greenmiststudios.zone.shared"
  compileSdk = libs.versions.android.compileSdk.get().toInteger()
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
  }
  defaultConfig {
    minSdk = libs.versions.android.minSdk.get().toInteger()
  }
}

sqldelight {
  databases {
    ZoneDatabase {
      packageName = "com.greenmiststudios.zone.db"
    }
  }
}
